name: Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  release:
    name: release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Trigger Docker Image Publish
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.get_tag.outputs.tag_name }}
        run: |
          gh workflow run --repo ${GITHUB_REPOSITORY} docker-build-push.yml -f ref=${TAG_NAME}
